name: my_portfolio
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  flutter_riverpod: ^2.4.9
  url_launcher: ^6.2.4
  flutter_animate: ^4.5.0
  rive: ^0.12.4
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets: 
    - assets/anims/

  fonts:
      - family: PersonalPortfolioIcons
        fonts:
          - asset: assets/fonts/PersonalPortfolioIcons.ttf
      - family: Product Sans
        fonts:
          - asset: assets/fonts/Product Sans Regular.ttf
          - asset: assets/fonts/Product Sans Bold.ttf
            weight: 900
          - asset: assets/fonts/Product Sans Italic.ttf
            style: italic